### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by veromeneses** [NoriSte/cypress-otp#25]
Hi, I'm wondering if we could have a new release since you've pushed commits to support Cypress 4+?

Thank you in advance!

**Comment by NoriSte** [comment]
Hi @veromeneses 
Thank you for letting me know that... Cypress is listed in the dependencies instead of the devdependencies. This is a mistake of mine, I should remove it from the dependencies...

Apart from that: do you have any problems using the plugin?

**Comment by veromeneses** [comment]
Hi @NoriSte, thank you for getting back to me!
 
No other issues so far, it works great and it was very easy to set up 😁

**Comment by NoriSte** [comment]
Removed Cypress from the dependencies and released the new version 😊
Thank you @veromeneses 
Stefano
