### ISSUE TITLE
Pre-requisite for using cypress-otp ??

### ISSUE THREAD

**Issue by arifmasood** [NoriSte/cypress-otp#41]
**Our use case is as below:**

We are automating an application, where we have to enter OTP - for mobile number verification. OTP is received via text message. Or we can access the database to get this OTP.

**How to use this plugin for our use case:**

Can you please share information whether this plugin can be used with any application. For our use case, does development team need to integrate it within their application code? Or just integrating within our automation code would be enough?

**Comment by NoriSte** [comment]
Hi @arifmasood 
This plugin is useful if you want to generate the OTP on the fly but your scenario is different. What you can do is:
- using this plugin: you copy-paste the secret used to generate the OTP in your test file
- without using this plugin: if you can read the OTP from the DB, do it! And this plugin is completely useless for you!

Let me know if it helps
Best
Stefano

**Comment by bhanupasham123** [comment]
Hi @NoriSte , You mentioned to use the 'YOUR_SECRET' in the below code. How can we generate the 'YOUR_SECRET' or from where we can get it?
cy.task("generateOTP", "YOUR_SECRET").then(token => {
  cy.get("#otp-token").type(token);
});
Thanks,
Bhanu

**Comment by NoriSte** [comment]
The Secret is the code you usually enter in your authentication app in order to allow it to generate OTPs. Are you in control of the OTP generation? Anyway, go for accessing the DB and you are ok 😉

**Comment by bhanupasham123** [comment]
@NoriSte  I am using azure authenticator to generate the otp code and i cannot see any secret there, Would this plugin work for azure MFA?

And also can you specify more on accessing DB to get the secret or otp please.

**Comment by arifmasood** [comment]
Thanks @NoriSte . Since we are not in control of generating OTP for application under test. So, we will go with approach where we get OTP from DB.

@bhanupasham123 how does OTP gets generated for system that you are testing. How do you get OTP. You will have to find a workaround by yourself considering your own factors.

@NoriSte, may be you can consider adding some information around this in your intro doc. I assume many others will also be having similar questions. Thanks much.

**Comment by NoriSte** [comment]
@bhanupasham123 
> I am using azure authenticator to generate the otp code

Ok, I guess that Azure Authenticator provided you a QR Code to be imported in an authenticator app? The QR Code is the secret 😉 the secret is shown once, if you want to see it again you have to disable and then re-enable the 2FA.

@arifmasood: you are right, I'd add that you need to be in control of generating the OTP secret to use this plugin, something like "*ATTENTION: this plugin does not manage third-party Authentication by itself! It allows you to generate always-fresh OTP codes if you own the secret code (usually shown when you the QR Code is shown), otherwise it is useless and you should manage authentication all your own.*"

What do you think?

**Comment by NoriSte** [comment]
@bhanupasham123 @arifmasood waiting for your feedback, tell me if the explanation would be ok 😉

**Comment by bhanupasham123** [comment]
@NoriSte When setting up azure registration on the authentication app there was code and URL and using both did not help to authenticate? You mentioned QR code is the secret so how do it generate the secret from QR code to add in to your script  cy.task("generateOTP", secret');
