### ISSUE TITLE
How to use this on subsequent MFA checks

### ISSUE THREAD

**Issue by ahoad** [NoriSte/cypress-otp#59]
Hi,

Thanks for a great tool! I've got it set up to generate the OTP from a QR code as part of an MFA set up on a login flow.

I also need to do a MFA check on subsequent logins and therefore provide a OTP password again, this time not from a QR code. 

I tried sending through the same code again but obviously this didn't work, so just wondering if there is a way to generate the OTP for this scenario?

**Comment by NoriSte** [comment]
Hi @ahoad, did you solve the problem on your own? 😊

**Comment by ahoad** [comment]
Hi, I thought I had as my test suddenly passed but it seemed to just be a fluke as it continued to fail afterwards. 
I couldn't work out how to generate this new token so I ended up using a different tool that allows you to generate new tokens based on the time.

**Comment by NoriSte** [comment]
Can you point me to the tool you used?
Thanks a lot, Amy 😊

**Comment by ahoad** [comment]
Sure :) it was this one: https://www.npmjs.com/package/otplib
