### ISSUE TITLE
Multiple attempts

### ISSUE THREAD

**Issue by omgui** [NoriSte/cypress-otp#62]
When two tests run that require otp - only the first runs successfully as the second call to generateOTP produces the same OTP and fails?

**Comment by NoriSte** [comment]
Never tested this scenario, could you create a minimal repo that reproduces the problem, please? So I can play with it and do some debugging 😊

**Comment by NoriSte** [comment]
I'm going to close this issue, feel free to re-open it with more details and a reproducible repository 😊

Thanks
Stefano

**Comment by omgui** [comment]
Thanks for Replying @NoriSte - I manage to get around it by adding a delay into each test of 30s - then when the next test runs it generates a new otp.
