### ISSUE TITLE
Invalid passcode after typing Token - Cypress 10

### ISSUE THREAD

**Issue by shastrisubramaniam** [NoriSte/cypress-otp#78]
I get an invalid passcode when I use cypress -otp.

Any help will be appreciated.

**Comment by NoriSte** [comment]
Hey! Can you share a minimal reproducible repo where I can play with it? Also, I'd like to know what the passcode the plugin generates compared to another app like Authy 😊

**Comment by shastrisubramaniam** [comment]
Oracle Authenticator is what I use and it generates token like 760312 while from cypress otp I see token like 449007.

**Spec file** 

/// <reference types="cypress" />

const { Runnable } = require("mocha")
beforeEach( () => {
  cy.on('uncaught:exception', (e,Runnable) => {
    console.log(e.message)
    if ( e.message.includes('r.sectionElement.displayHeaderText is not a function'))
    return false
  })
})
describe('login and create a new client',()=>{
    
  it('login by admin account',() => {
    const username = 'subbu@mailinator.com'
    const password = 'Napoleon#1234'
  cy.intercept('https://hcgbushareddev-ohrrqa.us-ashburn-1.ocs.oraclecloud.com/ords/r/ohrr/partner-portal/home').as('getHome')
  cy.visit("https://hcgbushareddev-ohrrqa.us-ashburn-1.ocs.oraclecloud.com/ords/r/ohrr/partner-portal/home", {failOnStatusCode:false})
  cy.wait('@getHome').then((interception) => {
  cy.get("#idcs-signin-basic-signin-form-username").type(username)
  cy.get("#idcs-signin-basic-signin-form-password").type(password)
  })
  cy.get("#idcs-signin-basic-signin-form-submit").click()
  cy.task('generateOTP', 'M2O3 BX4J 3SCW 6JUT JKMA FWX2 LM').then(token => {
  cy.get("#idcs-mfa-mfa-auth-passcode-input").type(token);
  cy.get("#ui-id-3").click()
  }); 
  })
})

**Cypress Config** 

const { defineConfig } = require("cypress");
module.exports = defineConfig({
  reporter: 'junit',
  reporterOptions: {
    mochaFile: 'results/my-test-output.xml',
    toConsole: true,
  },
  projectId: '4mreww',
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
        on("task", {
          generateOTP: require("cypress-otp")
        });
    },
  },
});
<img width="1512" alt="Screenshot 2023-11-30 at 11 26 28 AM" src="https://github.com/NoriSte/cypress-otp/assets/23286812/c86d7f4e-0122-4119-9115-36d2b7f9b181">

**Comment by NoriSte** [comment]
Did you run Oracle auth and cypress plugging at the same exact time?

**Comment by shastrisubramaniam** [comment]
Not exactly. I setup the manual key, set it up on my Mobile and enrolled for MFA/OTP and typed in my  token.I got logged in and then I clicked Logout.
I then used the Secret to login to the portal through Cypress.

**Comment by wyattpuckett** [comment]
Seeing the same issue today after having correct microsoft tokens running very frequently for the last year or so. It's still getting/inputting a token, just is an incorrect one now for whatever reason

**Comment by wyattpuckett** [comment]
Looks fixed now, at least in my case

**Comment by NoriSte** [comment]
@wyattpuckett did you do anything to fix it? I don't think the problem is in the plugin itself but at least @shastrisubramaniam could benefit from it.

**Comment by wyattpuckett** [comment]
Sorry to say that I didn't do anything, just resolved on its own somehow. Had never seen it input incorrect codes before, no clue what could've gone wrong

**Comment by shastrisubramaniam** [comment]
Does it have anything to do with the inability to handle spaces in secret ? I am unsure if cypress otp expects a secret in base32 format.We have been using a Java TOTP from taimos which works even now where we convert the ascii secret to bytes and hex.

**Comment by shastrisubramaniam** [comment]
Resolved after removing spaces.
